name: Linux Build & Unit Tests
on:
    pull_request: {}
    push: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
      id: go

    - name: Build Test
      run: |
        go test -v ./...